### ISSUE TITLE
Update "publish" Github Action to use .nvmrc file

### ISSUE THREAD

**Issue by david-chalk** [FusionAuth/fusionauth-vue-sdk#8]
Let's make the `publish` GitHub action look at the `.nvmrc` file to discover the correct version of Node to use when building. 

This will ensure that the CI/CD tooling uses the same Node version as the developers.

**Comment by JakeLo123** [comment]
Closing - https://github.com/FusionAuth/fusionauth-vue-sdk/pull/9
